# DB 생성

USE [master]
GO

/****** Object:  Database [coin]    Script Date: 2021-12-26 오후 6:43:49 ******/
CREATE DATABASE [coin]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'coin', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\coin.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'coin_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\coin_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [coin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [coin] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [coin] SET ANSI_NULLS OFF
GO

ALTER DATABASE [coin] SET ANSI_PADDING OFF
GO

ALTER DATABASE [coin] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [coin] SET ARITHABORT OFF
GO

ALTER DATABASE [coin] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [coin] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [coin] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [coin] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [coin] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [coin] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [coin] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [coin] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [coin] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [coin] SET  DISABLE_BROKER
GO

ALTER DATABASE [coin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [coin] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [coin] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [coin] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [coin] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [coin] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [coin] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [coin] SET RECOVERY FULL
GO

ALTER DATABASE [coin] SET  MULTI_USER
GO

ALTER DATABASE [coin] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [coin] SET DB_CHAINING OFF
GO

ALTER DATABASE [coin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [coin] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [coin] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [coin] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [coin] SET QUERY_STORE = OFF
GO

ALTER DATABASE [coin] SET  READ_WRITE
GO






# USER 생성

USE [coin]
GO
/****** Object:  User [coin_manager]    Script Date: 2021-12-26 오후 6:43:36 ******/
CREATE USER [coin_manager] FOR LOGIN [coin_manager] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [coin_manager]
GO
