spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
        generate-ddl: true

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;instanceName=coin
    username: coin_manager
    password: wpguq1986.

  decorator:
    datasource:
      p6spy:
        enable-logging: true
        multiline: true

